name: "Package Size Badge Action"
description: "Automatically calculate JavaScript bundle size and generate a badge"
author: "Timeo Williams"

inputs:
  path:
    description: "Path to the JS bundle"
    required: true
    default: "build/static/js/*.js"
  limit:
    description: "Size limit in KB"
    required: false
    default: "500 KB"
  label:
    description: "Badge label"
    required: false
    default: "Bundle Size"
  color:
    description: "Badge color"
    required: false
    default: "blue"
outputs:
  size:
    description: "The size of the bundle in KB"

runs:
  using: "node20"
  main: "size-limit.js"
  pre:
    - run: npm install size-limit @size-limit/preset-app
