name: "Run Size Limit Test"

on:
  push:
    branches:
      - main

jobs:
  run-size-limit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: List files in build directory
        run: ls -R build/static/js/

      - name: Run size-limit
        run: npx size-limit --json || node size-limit.js

    timeout-minutes: 10
